### ISSUE TITLE
customizing color and logos

### ISSUE THREAD

**Issue by samtux** [TomVer99/FHICT-typst-template#171]
I am new to Typst, and one of the reasons I started using it is because of this amazing template. I have a question regarding the customization of the template. I see that it's possible to add a logo and secondary color, but is there any reason why this option is not available for the rest of the logos and colors in the template? Is it possible for me to customize the logos and colors in my document without modifying the original template?

**Comment by TomVer99** [comment]
Hi there,
Thanks for your kind words 😄.
You cannot change the logos or colours without changing the original template. This might be a feature I will implement in the future, but this template is mainly focused on FHICT use so it will not happen soon.
