### ISSUE TITLE
Image Preview

### ISSUE THREAD

**Issue by NathanThus** [TomVer99/FHICT-typst-template#39]
It might be a good idea to add a few images for reference, as it's not clear as to what the template actually looks like.

**Comment by NathanThus** [comment]
> @NathanThus I implemented something that I think is what you mean, please let me know if you think it's a good implementation.

The title page looks great!
Might it be an idea to add a page as it would appear in the document itself?
This could include:
- A table
- Code snippet
- Some text (with headings)

**Comment by TomVer99** [comment]
> > @NathanThus I implemented something that I think is what you mean, please let me know if you think it's a good implementation.
> 
> The title page looks great! Might it be an idea to add a page as it would appear in the document itself? This could include:
> 
> * A table
> * Code snippet
> * Some text (with headings)

I have updated the Branch, let me know if you think it's good 😄

**Comment by NathanThus** [comment]
> > > @NathanThus I implemented something that I think is what you mean, please let me know if you think it's a good implementation.
> > 
> > 
> > The title page looks great! Might it be an idea to add a page as it would appear in the document itself? This could include:
> > 
> > * A table
> > * Code snippet
> > * Some text (with headings)
> 
> I have updated the Branch, let me know if you think it's good 😄

Absolutely perfect. Anyone using the template should now have a very clear idea of what the document will look like at the end. Thank you for taking the time to implement this!
