### ISSUE TITLE
License of the project

### ISSUE THREAD

**Issue by bbinet** [TomVer99/FHICT-typst-template#67]
Thank you for sharing this great typst template!

I would like to use it in my small 3-people company (after doing some minor colors updates).
What it the license of the project and is it allowed to use in a company?

**Comment by bbinet** [comment]
Ok thank you for your answer.
I will start from scratch using this template as a reference, and using parts of the code of this template, but won't reuse any styling of the template.

**Comment by TomVer99** [comment]
Best of luck!
